title: dgv
description: devlog
baseurl: ""
url: https://dgv.dev.br

theme: cvless

# site settings
taglong: devlog
tagshort:

# author settings
author:
  name: Daniel Gomes Vargas
  email: dgv@keemail.me
photo: assets/files/photo.jpg
address: Curitiba, Brazil

# social media links
profile:
  github: dgv
  bluesky: dgv.dev.br
  mastodon: mastodon.social/@dgv

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
