baseurl: "https://dgv.dev.br/"
languageCode: en-us
theme: enso
title: dgv
enableEmoji: true
enableRobotsTXT: true
pygmentsStyle: nord
menu:
  main: 
    - identifier: posts
      name: posts
      url: /posts/
      weight: 1
    - identifier: projects
      name: projects
      url: /projects/
      weight: 2
    - identifier: tips
      name: tips
      url: /tips/
      weight: 3
    - identifier: now
      name: now
      url: /now/
      weight: 4
params:
  abbrDateFmt: "Jan 2"
  author: "dgv"
  author.name: "Daniel Gomes Vargas"
  author.link: "dgv.dev.br"
  author.email: "dgv@keemail.me"
  dateFmt: "2006-01-02"
  description: "dgv's devlog & stuff"
  social:
    - name: codeberg.org/dgv
      url: https://codeberg.org/dgv
#    - name: crowdsupply.com/people/dgv
#      url: https://crowdsupply.com/people/dgv
    - name: github.com/dgv
      url: https://github.com/dgv
    - name: mastodon.social/@dgv
      url: https://mastodon.social/@dgv
#    - name: tangled.org/dgv.dev.br
#      url: https://tangled.org/dgv.dev.br
markup:
  goldmark:
    renderer:
      unsafe: true
