baseurl             = "https://dgv.dev.br/"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
author              = "Daniel Gomes Vargas"
title               = "dgv"
pygmentsuseclasses  = true
pygmentsStyle = "nord"
[markup.goldmark.renderer]
unsafe= true

[params]
  avatarAltText = "avatar"
  avatarSize = "size-m"
  avatarURL = "/img/dgv_dev_br.png"
  accentColor = "#8fbcbb"

  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css" integrity="sha384-5TcZemv2l/9On385z///+d7MSYlvIEw9FuZTIdZ14vJLqWphw7e7ZPuOiCHJcFCP" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js" integrity="sha384-cMkvdD8LoxVzGF/RPUKAcvmm49FQ0oxwDF3BGKtDXcEc+T1b2N+teh/OJfpU0jr6" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js" integrity="sha384-hCXGrW6PitJEwbkoStFjeJxv+fSOOQKOPbJxSfM6G5sWZjAyWhXiTIIAmQqnlLlh" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

  description = "programmer, entropist netrunner"
  footer = ""
  metaKeywords = ["blog", "devlog", "golang", "zig", "openbsd", "web3"]
  showBackToTopButton = true # true or false for "back to top" button on posts and pages

  socialIcons = [
    {name = "twitter", url = "https://x.com/dgvargas"},
    {name = "mastodon", url = "https://mastodon.social/@dgv"},
    {name = "github", url = "https://github.com/dgv"},
    {name = "linkedin", url = "https://linkedin.com/in/dgvargas/"},
    {name = "email", url = "mailto:danielgvargas@proton.me"}
  ]

[menu]   
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    name = "Tips"
    pre = "<span data-feather='info'></span>"
    url = "/tips/"
    weight = 6

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/dgv"
    weight = 7


  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = true
